name: ProMEP
channels:
  - anaconda
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - ld_impl_linux-64=2.39
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.39.4
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.7
  - python=3.8.13
  - readline=8.1.2
  - sqlite=3.39.4
  - tk=8.6.12
  - xz=5.2.6
  - nvidia-apex=0.1
  - cudatoolkit=11.6
  - pytorch=1.13.0
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - pytorch-cuda=11.6
  - emd=0.5.3
  - pythonnet=2.5.2
  - pip:
    - admin-torch==0.1.0
    - anykeystore==0.2
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - click==8.1.3
    - configparser==5.3.0
    - cryptacular==1.6.2
    - defusedxml==0.7.1
    - dgl==0.9.0
    - nvdllogger==1.0.0
    - docker-pycreds==0.4.0
    - e3nn==0.3.3
    - gitdb==4.0.9
    - gitpython==3.1.29
    - greenlet==2.0.1
    - h5py==3.7.0
    - hupper==1.10.3
    - idna==3.4
    - joblib==1.0.1
    - markupsafe==2.1.1
    - mpmath==1.2.1
    - munch==2.5.0
    - networkx==2.8.8
    - ninja==1.11.1
    - numpy==1.23.4
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - packaging==21.3
    - pandas==1.2.5
    - pastedeploy==3.0.1
    - pathtools==0.1.2
    - pbkdf2==1.3
    - pillow==9.3.0
    - pip==22.3.1
    - plaster==1.1
    - plaster-pastedeploy==1.0.1
    - promise==2.3
    - protobuf==3.20.1
    - psutil==5.9.4
    - pynvml==11.0.0
    - pyparsing==3.0.9
    - pyramid==2.0
    - pyramid-mailer==0.15.1
    - python-dateutil==2.8.2
    - python3-openid==3.2.0
    - pytz==2021.1
    - pyyaml==6.0
    - repoze-sendmail==4.4.1
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - scipy==1.9.3
    - sentry-sdk==1.11.0
    - setuptools==65.5.1
    - shortuuid==1.0.11
    - six==1.16.0
    - smmap==5.0.0
    - sqlalchemy==1.4.44
    - subprocess32==3.5.4
    - sympy==1.11.1
    - tensorboardx==2.5.1
    - tqdm==4.64.1
    - transaction==3.0.1
    - translationstring==1.4
    - typing==3.7.4.3
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - velruse==1.1.1
    - venusian==3.0.0
    - wandb==0.12.0
    - webob==1.8.7
    - wheel==0.38.4
    - wtforms==3.0.1
    - wtforms-recaptcha==0.3.2
    - zope-deprecation==4.4.0
    - zope-interface==5.5.2
    - zope-sqlalchemy==1.6
